name: laboratorio_controle
description: "A IoT Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  animated_splash_screen: ^1.3.0
  lottie: ^3.3.0
  mqtt_client: ^10.5.1
  provider: ^6.0.5
  video_player: ^2.8.3
  chewie: ^1.5.0
  connectivity_plus: ^6.1.4
  shared_preferences: ^2.5.2
  typed_data: ^1.4.0
  charts_flutter: ^0.12.0
  excel: ^4.0.6 
  path_provider: ^2.1.3 
  permission_handler: ^12.0.0+1
  open_filex: ^4.4.0
  flutter_native_splash: ^2.4.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/ConectandoBroker.json
    - assets/Error404.json
    - assets/IniciandoApp.json
    - assets/TudoCerto.json
    - assets/LogoUFU.PNG
    - assets/LogoUFU2.PNG
    - assets/LogoFEMEC.JPG
    - assets/SemInternet.json
    - assets/Tanque.json
    - assets/Alerta.json
    - assets/icone.png
    - assets/Ideia.json

  

